### ISSUE TITLE
Error: Cannot find module '/usr/local/node/project/webpack.config.js'

### ISSUE THREAD

**Issue by k00ni** [Dockerizing/NodeJS-NPM-ECMA6-Stack#6]
Using an empty folder as volume resulted in the following error:

```
npm WARN optional Skipping failed optional dependency /webpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN Bootstrap@1.0.0 No repository field.
npm WARN Bootstrap@1.0.0 No license field.
npm info ok 
module.js:341
    throw err;
    ^

Error: Cannot find module '/usr/local/node/project/webpack.config.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at module.exports (/usr/local/lib/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js:55:48)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

Please use an empty/default file, if it's not available. 

My start-command looks like:

```
docker run -v /home/k00ni/Documents/building-navigator:/usr/local/node/project -p 8080:8080 node-npm-stack
```

The folder _building-navigator_ only contained a LICENSE and README.md file.

**Comment by simeonackermann** [comment]
I think your folder wasn't empty. For a new project an empty folder is required to create the missing webpack config file etc.

**Comment by simeonackermann** [comment]
I'll point it in the coming readme.

**Comment by k00ni** [comment]
Done.
